name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: [""]

body:
  - type: markdown
    attributes:
      value: "**Describe the bug**"
  - type: textarea
    id: bug-description
    attributes:
      label: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true

  - type: markdown
    attributes:
      value: "**Type**"
  - type: checkboxes
    id: bug-type
    attributes:
      label: Which type of bug is this?
      options:
        - label: Symbol
        - label: Footprint
        - label: 3D Model
        - label: Simulation Model
        - label: Other (please specify)
    validations:
      required: true
  - type: input
    id: bug-other-type
    attributes:
      label: Please specify
      placeholder: Other type
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**To Reproduce**"
  - type: input
    id: bug-file
    attributes:
      label: Which file is causing the issue?
    validations:
      required: true

  - type: markdown
    attributes:
      value: "**Screenshots**"
  - type: input
    id: bug-screenshots
    attributes:
      label: If applicable, add screenshots to help explain your problem.

  - type: markdown
    attributes:
      value: "**Additional context**"
  - type: textarea
    id: bug-context
    attributes:
      label: Add any other context about the problem here, e.g. reference documents(attachment or url).