name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: [""]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true

  - type: dropdown
    id: bug-type
    attributes:
      label: Type
      description: Which type of bug is this?
      options:
        - Symbol
        - Footprint
        - 3D Model
        - Simulation Model
        - Other (please specify)
    validations:
      required: true
  - type: input
    id: bug-other-type
    attributes:
      label: Other type
      description: Please specify
      placeholder: Other type

  - type: input
    id: bug-file
    attributes:
      label: Bugged file
      description: Which file is causing the issue?
    validations:
      required: true

  - type: textarea
    id: bug-context
    attributes:
      label: Addional context
      description: |
        If applicable, add screenshots to help explain your problem.
        You can also provide any other context here, such as reference documents.
        These can be attachments or URLs.